title: DEFCON 1 Restoration Services
description: >- # this means to ignore newlines until "baseurl:"
  DEFCON 1 Restoration Services DFW Argyle Texas, Call 940-240-0911
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://defcon1dfw.com" # the base hostname & protocol for your site, e.g. http://example.com
urlPrefix: /
domainName: defcon1dfw.com

facebookUser: defcon1dfwrestoration
linkedinUser: defcon1dfw
xUser: defcon1dfw
instagramUser: defcon1dfw

navTheme: dark
mainTheme: light
navLogo: assets/img/primary-logo.png

dbaOneName: "DEFCON 1"
dbaTwoName: "Restoration Services"

author: Defcon1dfw

copy: "© 2025 Copyright: defcon1dfw.com"

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

yt_url_base: "https://youtube.com/"
yt_url_watch: "https://www.youtube.com/embed/"
yt_img_url_base: "https://img.youtube.com/vi/"

dfwGoogleMap: "https://www.google.com/maps/place/Dallas-Fort+Worth+Metropolitan+Area,+TX/@32.7413461,-97.6229323,9z/data=!4m6!3m5!1s0x864e82b81f3a3a2d:0x53724d9a808b8ce5!8m2!3d32.7078751!4d-96.9209135!16zL20vMDF3amYw"
