title: DEFCON 1 Restoration Services
description: >- # this means to ignore newlines until "baseurl:"
  DEFCON 1 Restoration Services DFW
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://defcon1dfw.com" # the base hostname & protocol for your site, e.g. http://example.com
urlPrefix: /
domainName: defcon1dfw.com

navTheme: dark
mainTheme: light
navLogo: assets/img/primary-logo.png

dbaOneName: "DEFCON 1"
dbaTwoName: "Restoration Services"

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
