title: DEFCON 1 Restoration Services
description: >- # this means to ignore newlines until "baseurl:"
  DEFCON 1 Restoration Services DFW Argyle Texas, Call 940-240-0911
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://defcon1dfw.com" # the base hostname & protocol for your site, e.g. http://example.com
urlPrefix: /
domainName: defcon1dfw.com

facebookUser: defcon1dfwrestoration
linkedinUser: defcon1dfw
xUser: defcon1dfw
instagramUser: defcon1dfw

navTheme: dark
mainTheme: light
navLogo: assets/img/primary-logo.png

dbaOneName: "DEFCON 1"
dbaTwoName: "Restoration Services"

author: Defcon1dfw

copy: "© 2025 Copyright: defcon1dfw.com"

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

yt_url_base: "https://youtube.com/"
yt_url_watch: "https://www.youtube.com/embed/"
yt_img_url_base: "https://img.youtube.com/vi/"

dfwGoogleMap: "https://www.google.com/maps/@32.946517,-96.9641822,11z?entry=ttu&g_ep=EgoyMDI1MDIxOC4wIKXMDSoASAFQAw%3D%3D"
