title: DEFCON 1 Restoration Services
description: >- # this means to ignore newlines until "baseurl:"
  DEFCON 1 Restoration Services DFW
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://defcon1dfw.com" # the base hostname & protocol for your site, e.g. http://example.com
urlPrefix: /
domainName: defcon1dfw.com

navTheme: dark
mainTheme: light
navLogo: assets/img/primary-logo.png

dbaOneName: "DEFCON 1"
dbaTwoName: "Restoration Services"

# Build settings
plugins:
  - jekyll-sitemap
#   - jekyll-seo-tag

yt_url_base: "https://youtube.com/"
yt_url_watch: "https://www.youtube.com/embed/"
yt_img_url_base: "https://img.youtube.com/vi/"
